### PR TITLE
respect fenced blocks wrapped into ```

### PR DESCRIPTION
**Pull request by syavorsky**
@brettz9 how about this approach? I see what you are proposing with `check()` option in  #64, but it seems like that way we would ask too much work from lib user.

### CODE REVIEW

**Comment by brettz9** [comment]
That looks so much nicer!

My only thought is maybe accepting a callback for `opts.fence`, passing it the current `isFenced`state (so it can return a truthy or falsey value). I probably should have tightened up my earlier implementation that relied on `includes` (which is safe to use in place of `indexOf` in your `engines` target of Node>=6) to avoid say `````@example ```some inline code``` ````` from preventing detection of future tags.

**Comment by brettz9** [comment]
So in place of:

```js
if (line.source.indexOf(opts.fence) !== -1) {
```

just:

```js
if (opts.fence && opts.fence(line.source, state.isFenced)) {
```

**Comment by syavorsky** [comment]
allowing a function alternative for `opts.fence` is a great idea, let me tweak it

**Comment by syavorsky** [comment]
@brettz9 allowed custom function for `opts.fence` as you suggested, and added more tests for quirk cases. One thing I am still missing is what was your idea with `opts.fence(line.source, state.isFenced)`. Can you explain on example how we can make use of a second argument please

**Comment by brettz9** [comment]
I think your modulo addition takes care of things as far as I can tell, so no need to pass it the second argument I think.

**Pull request merged**
