### PR TITLE
feat: dedent spacing

### LINKED ISSUE #146: feat: { spacing: 'dedent' }
Let's give users a middle ground between 'compact' and 'preserve':
```js
/**
 * @fires {CustomEvent<{ component: PfeClipboard }>} copied
 *        Fires when the current url is successfully copied the user's system clipboard.
 *
 *        ```js
 *        detail: {
 *          url: string
 *        }
 *        ```
 *
 */
```
```js
console.log(parse(comment, { spacing: 'dedent' }.tags[0].description)
```
`````markdown
Fires when the current url is successfully copied the user's system clipboard.

```js
detail: {
  url: string
}
```
`````

this shouldn't be hard to implement, it's basically:
1. get the value if spacing was 'preserve'
2. run `dedent` from 'dedent' npm package on the result

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #146

### CODE REVIEW

**Comment by syavorsky** [comment]
@bennypowers thanks for the PR, but I want to circle back to what I was suggesting in #146 comments
> The spacing option was intentionally kept limited to avoid complexity. 

I don't agree with allowing  `spacing: 'dedent'`.  That option got to stay simple as is. For all other transformations, I suggest applying them as in [this example](https://syavorsky.github.io/comment-parser/#stringify-formatting) without touching top-level API. Indentation is not a parsing option but rather a transformation you apply to the tokenized source. So for the `dedent` it would look like

```ts
const { dedent } = transforms;
const parsed = parse(source);
const stringified = stringify(dedent(parsed[0]));
```

all config permutations handled in the main flow were a huge pain in 0.x version. On other hand, using [flow()](https://github.com/syavorsky/comment-parser/blob/master/src/transforms/index.ts#L5) allows customizing the flow with interference

if you still willing to land this contribution, can we shape it after `transforms/align.ts` which is a pretty similar transformation? So it will boil down to

```
transforms/dedent.ts
tests/unit/transforms-align.spec.ts
tests/e2e/transforms.spec.js
```

**Comment by bennypowers** [comment]
doing so would require reimplementing dedent to take markers and return a Transform, when it's already implemented as string => string. What do you think?

**Comment by syavorsky** [comment]
Yes, `dedent` would have to be a function returning configured `Transform`. It's the already existing flow for `align` and `indent`, there is no good reason `dedent` should be one-off

**Comment by bennypowers** [comment]
Unfortunately I don't have the time right now to rewrite an [existing package](https://npm.im/dedent) to suit the custom tokenizer that comment-parser uses. I think it would be a great feature but for now I'll have to apply workarounds like dedenting the output in my consuming code.

Thanks for considering this PR

**Comment by syavorsky** [comment]
@bennypowers no prob. Thanks for the feature suggestion, I will try to land it myself sometime.

**Pull request closed without merging**
