### PR TITLE
Native ESM

### PR DESCRIPTION
**Pull request by brettz9**
- feat: support native ESM

Currently, since `type: 'module'` was lacking in `package.json`, native Node ESM would try to load the CJS files by default. (The `exports.default` in CJS would require any use of the ESM import to add `.default` to the imported object since Node uses `module.exports` (and not `.defaults`) per https://nodejs.org/api/esm.html#esm_import_statements .)

The jest file does not use a JSON export since this is only experimental in Node.

The reason for the build script addition is that TS lacks an option to export with the ".js" which native ESM not only in the browser but also in Node expects for relative paths. See https://nodejs.org/api/esm.html#esm_mandatory_file_extensions and  https://stackoverflow.com/a/62626938/271577

There also seemed to have been a package installation problem, so also rebuilt the entire package-lock.json file.

### CODE REVIEW

**Review by syavorsky — APPROVED** [review]

**Comment by syavorsky** [comment]
@brettz9 thanks for tweaking it, do you think build 10.x/12.x builds fail because of this change?

**Comment by brettz9** [comment]
Ah yes, sorry hadn't noticed. Yeah, `engines` should be updated, and Node 10 has been end-of-lifed. That's part of the reason the transition to ESM has begun. But as far as 12 failing, I'm trying to investigate why that might be. I tried updating devDependencies and prettifying and that helped with one issue, but still have another.

**Comment by brettz9** [comment]
Tests passing now, as I updated CI (as well as `engines`). Btw, I updated the Travis file as well, but did you mean to have that now that you have the GitHub action?

**Comment by brettz9** [comment]
Also, are you opposed to having eslint in the new project?

**Pull request merged**
