### PR TITLE
allow for valid empty jsdoc; fixes #128

### LINKED ISSUE #128: Support `/** */`
Not a useful scenario, admittedly, but I think `/** */` technically is valid jsdoc but is just getting an empty array without tokens. Trying to ensure covering all bases re: edge cases. It works with a tag, however.

### PR DESCRIPTION
**Pull request by brettz9**
I added the `\x20` markers at the end of line as my IDE does auto-trimming. Let me know if you need me to remove.

### CODE REVIEW

**Comment by brettz9** [comment]
Hi... Think you could take a look, @syavorsky ?

**Comment by syavorsky** [comment]
I am a bit busy right now along with other Ukrainians

**Comment by brettz9** [comment]
🇺🇦 I wish you and your loved ones well...

**Comment by syavorsky** [comment]
@brettz9 thanks for the contribution, merging

**Comment by syavorsky** [comment]
published in `comment-parser@1.3.1`

**Pull request merged**
