### PR TITLE
Option docs

### PR DESCRIPTION
**Pull request by brettz9**
documents `parse` options (in README and with additions/changes in TypeScript).

### CODE REVIEW

**Comment by brettz9** [comment]
I can amend this and rebase on #66 when it may be ready.

**Comment by brettz9** [comment]
I've rebased and amended. I also added a script to check the typescript declaration file validity.

**Comment by syavorsky** [comment]
@brettz9 great contribution, thanks!

**Comment by syavorsky** [comment]
@brettz9 `+ comment-parser@0.7.0`

**Pull request merged**
